name: dotnet5-testapis-docker-acr-azureappservice

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGEM_AZURECR: ${{ secrets.AZURECR_REGISTRY }}/apifinancas-dotnet5
  CAMINHO_PROJETO_TESTES: ./APIFinancas.Especificacoes
  CAMINHO_PROJETO_WEBAPP: ./APIFinancas
  NOME_WEBAPP: groffe-apifinancas

jobs:
  build-docker-tests-push-acr:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build de imagem
      run: |
        cd ${{ env.CAMINHO_PROJETO_WEBAPP }}
        docker build . --file Dockerfile --tag ${{ env.IMAGEM_AZURECR }}:latest

    - name: Criação de container para testes com a API
      run: |
        docker run --name api-testes -p 1234:80 -d ${{ env.IMAGEM_AZURECR }}:latest
        docker container ls
        
    - name: Testes com .NET 5 + SpecFlow + xUnit + Refit
      env:
        UrlWebAppTestes: http://localhost:1234
      run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} --verbosity minimal
      
    - name: Login no Azure Container Registry
      uses: docker/login-action@v1.8.0
      with:
        registry: ${{ secrets.AZURECR_REGISTRY }}
        username: ${{ secrets.AZURECR_USERNAME }}
        password: ${{ secrets.AZURECR_PASSWORD }}

    - name: Geração de tag com número do Build e Push no Azure Container Registry
      run: |
        docker tag ${{ env.IMAGEM_AZURECR }}:latest ${{ env.IMAGEM_AZURECR }}:$GITHUB_RUN_NUMBER
        docker push ${{ env.IMAGEM_AZURECR }}
        
  deployment-azwebapp:
    needs: [build-docker-tests-push-acr]

    runs-on: ubuntu-latest

    steps:
    - name: Azure Login - Conectando com Credenciais no Azure
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure WebApp - Deployment da Aplicacao
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.NOME_WEBAPP }}
        images: '${{ env.IMAGEM_AZURECR }}:${{ github.run_number }}'